/**
 * attacks.test.ts — nonce reuse and binding consistency, checked against the real
 * @noble/curves Ed25519 verifier.
 *
 * Teeth:
 *  - an honest FROST(Ed25519) aggregate verifies (the pipeline is real, not a
 *    stub) — if it didn't, every attack claim would be meaningless;
 *  - nonce reuse across three sessions recovers the EXACT group secret and the
 *    forged signature is ACCEPTED by the real verifier;
 *  - fresh nonces (control) recover the wrong key and the forgery is REJECTED;
 *  - dropping the RFC 9591 binding factor at aggregation makes the real verifier
 *    REJECT, while the correctly-bound aggregate is ACCEPTED.
 */

import { describe, expect, it } from 'vitest';
import {
  keygen,
  frostSign,
  lagrangeCoeff,
  runNonceReuse,
  runBindingOmission,
  bindingFactor,
  bindingFactorInput,
} from './attacks';
import { ed25519 } from '@noble/curves/ed25519.js';

const B = ed25519.Point.BASE;
const L = ed25519.Point.Fn.ORDER;
const mod = (x: bigint): bigint => ((x % L) + L) % L;

describe('real FROST(Ed25519) pipeline', () => {
  it('an honest t-of-n aggregate verifies under the real Ed25519 verifier', async () => {
    const group = keygen(2, 3);
    const set = group.signers.slice(0, 2);
    const nonces = new Map(
      set.map((s) => [
        s.id,
        { d: mod(BigInt(`0x${s.id}9a3f`) + 7n), e: mod(BigInt(`0x${s.id}c1d2`) + 11n) },
      ]),
    );
    const out = await frostSign(group, set, 'hello', nonces);
    expect(out.verified).toBe(true);
  });

  it('Lagrange coefficients reconstruct the group secret from any threshold subset', () => {
    const group = keygen(3, 5);
    const set = group.signers.slice(1, 4); // arbitrary 3-of-5 subset
    const ids = set.map((s) => s.id);
    let x = 0n;
    for (const s of set) x = mod(x + mod(lagrangeCoeff(s.id, ids) * s.share));
    expect(x).toBe(group.secret);
    expect(B.multiply(x).toBytes()).toEqual(group.publicKeyEnc);
  });
});

describe('Attack 1 — nonce reuse across signing attempts', () => {
  it('reuse ⇒ recovers the exact group secret and the forgery is ACCEPTED', async () => {
    const r = await runNonceReuse(true);
    expect(r.sessionsVerified).toBe(true);
    expect(r.recoveredSecretHex).toBe(r.secretHex);
    expect(r.keyRecovered).toBe(true);
    expect(r.forgeryAccepted).toBe(true);
  });

  it('fresh nonces (control) ⇒ wrong key, forgery REJECTED', async () => {
    const r = await runNonceReuse(false);
    expect(r.sessionsVerified).toBe(true);
    expect(r.keyRecovered).toBe(false);
    expect(r.forgeryAccepted).toBe(false);
  });
});

describe('Binding-term consistency experiment', () => {
  it('original accepts, only-R mutation rejects, consistent unbound honest control accepts', async () => {
    const r = await runBindingOmission();
    expect(r.boundVerified).toBe(true);
    expect(r.unboundVerified).toBe(false);
    expect(r.honestUnboundVerified).toBe(true);
    expect(r.alteredSignatureHex.slice(64)).toBe(r.boundSignatureHex.slice(64));
    expect(r.alteredSignatureHex.slice(0, 64)).not.toBe(r.boundSignatureHex.slice(0, 64));
  });
});

// Independent published expectations: RFC 9591 Appendix E.1, not values
// generated by this implementation. https://www.rfc-editor.org/rfc/rfc9591#appendix-E.1
const bytes = (s: string) => Uint8Array.from(s.match(/../g)!, x => parseInt(x, 16));
const scalar = (s: string) => BigInt('0x' + Array.from(bytes(s)).reverse().map(x => x.toString(16).padStart(2, '0')).join(''));
const encodedScalar = (n: bigint) => n.toString(16).padStart(64, '0').match(/../g)!.reverse().join('');
const encodedBytes = (b: Uint8Array) => Array.from(b, x => x.toString(16).padStart(2, '0')).join('');
const pk = bytes('15d21ccd7ee42959562fc8aa63224c8851fb3ec85a3faf66040d380fb9738673');
const message = bytes('74657374');
const commitments = [
  { id: 1n, D: bytes('b5aa8ab305882a6fc69cbee9327e5a45e54c08af61ae77cb8207be3d2ce13de3'), E: bytes('67e98ab55aa310c3120418e5050c9cf76cf387cb20ac9e4b6fdb6f82a469f932') },
  { id: 3n, D: bytes('cfbdb165bd8aad6eb79deb8d287bcc0ab6658ae57fdcc98ed12c0669e90aec91'), E: bytes('7487bc41a6e712eea2f2af24681b58b1cf1da278ea11fe4e8b78398965f13552') },
];
const prefix = '15d21ccd7ee42959562fc8aa63224c8851fb3ec85a3faf66040d380fb9738673504df914fa965023fb75c25ded4bb260f417de6d32e5c442c6ba313791cc9a4948d6273e8d3511f93348ea7a708a9b862bc73ba2a79cfdfe07729a193751cbc973af46d8ac3440e518d4ce440a0e7d4ad5f62ca8940f32de6d8dc00fc12c660b817d587d82f856d277ce6473cae6d2f5763f7da2e8b4d799a3f3e725d4522ec7';

describe('RFC 9591 Ed25519 Appendix E.1 known answers', () => {
  it('matches both exact binding inputs and factors', async () => {
    for (const [id, expected] of [
      [1n, 'f2cb9d7dd9beff688da6fcc83fa89046b3479417f47f55600b106760eb3b5603'],
      [3n, 'b087686bf35a13f3dc78e780a34b0fe8a77fef1b9938c563f5573d71d8d7890f'],
    ] as const) {
      expect(encodedBytes(await bindingFactorInput(id, pk, message, commitments))).toBe(prefix + encodedScalar(id));
      expect(encodedScalar(await bindingFactor(id, pk, message, commitments))).toBe(expected);
    }
  });

  it('matches published response shares and aggregate signature', async () => {
    const set = [
      { id: 1n, share: scalar('929dcc590407aae7d388761cddb0c0db6f5627aea8e217f4a033f2ec83d93509') },
      { id: 3n, share: scalar('d3cb090a075eb154e82fdb4b3cb507f110040905468bb9c46da8bdea643a9a02') },
    ];
    const group = { threshold: 2, secret: scalar('7b1c33d3f5291d85de664833beb1ad469f7fb6025a0ec78b3a790c6e13a98304'), publicKeyEnc: pk, signers: set };
    const nonces = new Map([
      [1n, { d: scalar('812d6104142944d5a55924de6d49940956206909f2acaeedecda2b726e630407'), e: scalar('b1110165fc2334149750b28dd813a39244f315cff14d4e89e6142f262ed83301') }],
      [3n, { d: scalar('c256de65476204095ebdc01bd11dc10e57b36bc96284595b8215222374f99c0e'), e: scalar('243d71944d929063bc51205714ae3c2218bd3451d0214dfb5aeec2a90c35180d') }],
    ]);
    const out = await frostSign(group, set, 'test', nonces);
    expect(out.verified).toBe(true);
    expect(out.shares.map(s => encodedScalar(s.z))).toEqual([
      '001719ab5a53ee1a12095cd088fd149702c0720ce5fd2f29dbecf24b7281b603',
      'bd86125de990acc5e1f13781d8e32c03a9bbd4c53539bbc106058bfd14326007',
    ]);
    expect(encodedBytes(out.signature)).toBe('36282629c383bb820a88b71cae937d41f2f2adfcc3d02e55507e2fb9e2dd3cbebd9d2b0844e49ae0f3fa935161e1419aab7b47d21a37ebeae1f17d4987b3160b');
  });

  it('binds the public key, message, commitment list and participant identifier', async () => {
    const expected = await bindingFactor(1n, pk, message, commitments);
    const otherPk = pk.slice(); otherPk[0] = otherPk[0]! ^ 1;
    expect(await bindingFactor(1n, otherPk, message, commitments)).not.toBe(expected);
    expect(await bindingFactor(1n, pk, new TextEncoder().encode('altered'), commitments)).not.toBe(expected);
    expect(await bindingFactor(1n, pk, message, [commitments[0]!])).not.toBe(expected);
    expect(await bindingFactor(3n, pk, message, commitments)).not.toBe(expected);
  });

  it('rejects unordered, duplicate, zero and absent identifiers', async () => {
    await expect(bindingFactor(1n, pk, message, [...commitments].reverse())).rejects.toThrow();
    await expect(bindingFactor(1n, pk, message, [commitments[0]!, commitments[0]!])).rejects.toThrow();
    await expect(bindingFactor(0n, pk, message, commitments)).rejects.toThrow();
    await expect(bindingFactor(2n, pk, message, commitments)).rejects.toThrow();
  });
});
